name: noto
description: "Noto is a modern, intuitive note-taking app designed for simplicity and efficiency. Whether you're jotting down ideas, organizing tasks, or keeping track of important information, Noto offers a streamlined user experience that puts your notes front and center. With features like rich text editing, color-coded notes, pinning, and dark mode, Noto is built to adapt to your personal style and needs."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^10.1.9
  google_fonts: ^6.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  popover: ^0.3.0+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
